### ISSUE TITLE
Remove need for "use std::ops"

### ISSUE THREAD

**Issue by brianwp3000** [brianwp3000/impl_ops#7]
The best solution would be to have ```impl_ops!``` put all its logic into its own mod and put ```use std::ops``` in there, but that would require the user to input a unique mod name into the macro and that's incredibly annoying.
If only there were a way for macros to generate a guaranteed unique ```ident```...

**Comment by mutantbob** [comment]
Is this the kind of problem that can be solved by having the macro body use `$crate::_parse_binary_op` ?

**Comment by brianwp3000** [comment]
Hey FYI this repo has been deprecated in favor of https://github.com/carbotaniuman/auto_ops. It looks like they might have already fixed this issue over there—their README example doesn’t have the `use std::ops`
